name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          apiKey: ${{ secrets.OPENAI_API_KEY }}
          prompt: 'Please generate a haiku about the following topic'
          input: 'Github Actions'
          model: 'gpt-4'
          temperature: 1
          max_tokens: 200

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.completion}}"
